[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.12",
    "matplotlib>=3.10.1",
    "numpy>=2.2.5",
    # "opencv-python>=4.11.0.86",
    "pillow>=11.2.1",
    # "pycuda>=2025.1",
    "pydantic>=2.11.4",
    "python-dotenv>=1.1.0",
    "python-jose[cryptography]>=3.4.0",
    "python-multipart>=0.0.20",
    # "scikit-learn>=1.6.1",
    "requests>=2.32.3",
    "seaborn>=0.13.2",
    "starlette>=0.46.2",
    # "tensorrt>=10.9.0.34",
    # "torch>=2.7.0",
    # "torchaudio>=2.7.0",
    # "torchvision>=0.22.0",
    "uvicorn>=0.34.2",
]
